services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200' # Match this with your NestJS server port
    env_file:
      - .env # Loads environment variables (DATABASE_URL)
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - '2000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
